FILLERS = [
    # Basic polite modals
    "can you",
    "could you",
    "would you",
    "will you",
    "can you please",
    "could you please",
    "would you please",
    "will you please",

    # Slightly more formal / indirect
    "would you mind",
    "would you mind if you",
    "do you mind",
    "do you mind if you",
    "is it possible to",
    "is it possible for you to",
    "would it be possible to",
    "would it be possible for you to",
    "could it be possible to",
    "could it be possible for you to",

    # Softening with “just”, “maybe”, “possibly”
    "could you just",
    "can you just",
    "would you just",
    "can you maybe",
    "could you maybe",
    "would you maybe",
    "can you possibly",
    "could you possibly",
    "would you possibly",
    "if you could",
    "if you could just",
    "if you can",
    "if you can just",

    # Please variants
    "please",
    "please can you",
    "please could you",
    "please would you",
    "please will you",

    # More indirect / hedgey
    "i was wondering if you could",
    "i was wondering whether you could",
    "i was wondering if you would",
    "i was wondering whether you would",
    "i was hoping you could",
    "i was hoping you would",
    "do you think you could",
    "do you think you can",
    "do you think you would",
    "do you think you might",
    "any chance you could",
    "any chance you can",
    "is there any chance you could",
    "is there any chance you can",

    # Casual / conversational
    "can you do me a favor and",
    "could you do me a favor and",
    "would you do me a favor and",
    "do me a favor and",
    "could you help me",
    "can you help me",
    "can you help me to",
    "could you help me to",
    "could you help me with",
    "can you help me with",

    # Sentence-final softeners (suffix-like)
    "please, if you can",
    "please, if you could",
    "if that’s okay",
    "if that’s alright",
    "if that’s all right",
    "if you don’t mind",
    "if you wouldn’t mind",
    "if possible",
    "when you get a chance",
    "whenever you get a chance",
    "when you have time",
    "when you have a moment",
    "when you have a sec",
    "at your convenience",

    'assitant',
    'tess',
    'i want',
    'i want to',
    'i want the',
]