from pathlib import Path

SEMANTIC_WEIGHT = 0.7
LEXICAL_WEIGHT = 0.2
OVERLAP_BOOST_MAX = 0.05
CONFIDENCE_THRESHOLD = 0.85
PARAM_BOOST_MULTIPLIER = 1.1
HIGH_CONFIDENCE_THRESHOLD = 0.85
AMBIGUITY_THRESHOLD = 0.1
MODEL_NAME = "MongoDB/mdbr-leaf-ir"
SPACY_MODEL_NAME = "en_core_web_sm"
CACHE_DIR = Path("cache")