//! Declarative skill definition.
//!
//! [`skill!`] is the single entry point for defining a
//! [`Skill`](crate::registry::Skill). It expands to the full `impl Skill for
//! <Type>` block — the struct, `name()`, `intents()`, and the `BoxFuture`/`Box::pin`
//! wiring for `execute()` — so a skill author writes only the parts that are
//! actually specific to their skill: the intent catalog and the execution body.
//!
//! This keeps [`SkillRegistry`](crate::registry::SkillRegistry) and the parser
//! closed for modification: adding a capability means writing one `skill!` block
//! in a new file and listing it in
//! [`skills::all`](crate::registry::skills::all); nothing in the registry, the
//! parser, or `main.rs` ever needs to change.
#[macro_export]
macro_rules! skill {
    (
        struct $struct_name:ident;
        name = $skill_name:literal;
        $(
            intent $intent_id:literal {
                desc: $desc:literal,
                args: [ $( $arg:expr ),* $(,)? ],
                exemplars: [ $( $exemplar:literal ),+ $(,)? ],
                risk_level: $risk_level:expr,
            }
        )+
        execute($cmd:ident) $body:block
    ) => {
        /// Skill definition generated by the `skill!` macro; see its declaration
        /// site for the intents it handles.
        pub struct $struct_name;

        impl $crate::registry::Skill for $struct_name {
            fn name(&self) -> &'static str {
                $skill_name
            }

            fn intents(&self) -> ::std::vec::Vec<$crate::registry::IntentDescriptor> {
                ::std::vec![
                    $(
                        $crate::registry::IntentDescriptor::new(
                            $intent_id,
                            $desc,
                            {
                                // A plain `&[ $arg ),* ]` here is a temporary: rvalue
                                // static promotion only applies to literals, not to
                                // `const fn` calls like `ArgSpec::optional(..)` in a
                                // non-const expression position. Binding it through a
                                // block-scoped `const` forces real const evaluation, so
                                // the array itself has `'static` storage.
                                const ARGS: &[$crate::registry::ArgSpec] = &[ $( $arg ),* ];
                                ARGS
                            },
                            &[ $( $exemplar ),+ ],
                            $risk_level,
                        ),
                    )+
                ]
            }

            fn execute<'a>(
                &'a self,
                $cmd: &'a $crate::events::Event,
            ) -> $crate::registry::BoxFuture<
                'a,
                ::std::result::Result<$crate::registry::ExecutionResult, ::anyhow::Error>,
            > {
                ::std::boxed::Box::pin(async move { $body })
            }
        }
    };
}
